language: php

php:
  - 7.1
  - 7.2

env:
  APP_ENV: testing
  APP_KEY: Tgm8GqW1Ldao5Q8maftoViYeKOWgrFE1
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit;
